server:
   port: 8086
eureka:
   client:
     registerWithEureka: false
     fetchRegistry: false
     serviceUrl:
      defaultZone: http://localhost:8086/eureka/
   instance:
     hostname:backup
spring: 
   application:
     name: eureka-server